[project]
name = "symmetrical-nba-potato"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "curl-cffi>=0.13.0",
    "httpx[http2]>=0.28.1",
    "slack-sdk>=3.37.0",
]
